// Komponen utama yang mengatur tampilan dasar aplikasi
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// Inisialisasi font Inter
const inter = Inter({ subsets: ['latin'] });

// Metadata untuk SEO
export const metadata: Metadata = {
  title: 'Simple Push Notif Next.js',
  description: 'Generated by create next app',
};

// Komponen layout utama yang membungkus semua halaman
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Menggunakan MVP.css untuk styling dasar */}
        <link rel="stylesheet" href="https://unpkg.com/mvp.css" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
